Bundle contest style and scoreboard Uriel endpoints
ia-toki/judgels pull request #114
Opened 2019-02-27 09:58 UTC by nathanchrs

Uriel endpoints for #111.

2019-02-27 17:24 UTC, fushar requested changes

2019-02-27 17:24 UTC, fushar commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/scoreboard/ScoreboardState.java
> +    List<Optional<Integer>> getProblemItems();
So as discussed, please remove this

2019-02-28 02:48 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/test/java/judgels/uriel/contest/scoreboard/gcj/GcjScoreboardProcessorTests.java
> +                    new ArrayList<>(),
```suggestion
                    ImmutableList.of(),
```

(all changes)

2019-02-28 07:29 UTC, nathanchrs commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/scoreboard/ScoreboardState.java
> +    List<Optional<Integer>> getProblemItems();
Removed

2019-02-28 07:33 UTC, nathanchrs commented on judgels-backends/uriel/uriel-app/src/test/java/judgels/uriel/contest/scoreboard/gcj/GcjScoreboardProcessorTests.java
> +                    new ArrayList<>(),
Replaced

2019-02-28 07:39 UTC, fushar requested changes

2019-02-28 07:39 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/bundle/BundleScoreboardProcessor.java
> +public class BundleScoreboardProcessor implements ScoreboardProcessor {
Tests?

2019-02-28 13:04 UTC, fushar approved these changes

2019-02-28 14:00 UTC, merged

2019-03-01 12:39 UTC, nathanchrs commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/bundle/BundleScoreboardProcessor.java
> +public class BundleScoreboardProcessor implements ScoreboardProcessor {
Will be added in another PR.