Implement short answer form
ia-toki/judgels pull request #142
Opened 2019-03-13 16:12 UTC by chidx

Implementing the short answer form based on #122 

Here are the screenshots:
![Screenshot from 2019-03-13 17-03-17](https://user-images.githubusercontent.com/2063523/54295187-dca7f200-45b2-11e9-862d-7a0953e337d0.png)

![Screenshot from 2019-03-13 17-03-37](https://user-images.githubusercontent.com/2063523/54295203-e2053c80-45b2-11e9-828d-f0702eab46dd.png)

![Screenshot from 2019-03-13 17-03-59](https://user-images.githubusercontent.com/2063523/54295214-e6315a00-45b2-11e9-9a3b-530928c69de6.png)

2019-03-14 02:04 UTC, fushar requested changes

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +            Belum ada jawaban
```suggestion
            Not answered yet.
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +            Menyimpan jawaban...
```suggestion
            Saving answer...
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +            Jawaban Tersimpan!
```suggestion
            Answer saved!
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +          <strong>Format jawaban salah</strong>
```suggestion
          <strong>Wrong answer format!</strong>
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +    if (this.state.wrongFormat) {
```
return this.state.wrongFromat && (
  <Callout ...
  ...
);
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +    let readOnly = false;
```
const readOnly = this.state ....
```

2019-03-14 02:04 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +    if (this.state.answerState === AnswerState.Answering) {
```
return this.state.answerState === AnswerState.Answering && (
  <Button ...
  ...
);
```

2019-03-14 20:30 UTC, chidx commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +        if (val === 1) {
There is no other possible value beside `1`, do you mean that I can change it to: `if (val)` ?

2019-03-14 20:50 UTC, chidx commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +  fill: boolean = true;
Yes. I make it a class member because I got tslint warning when I provide `true` value on `fill` props of `<ControlGroup>` inside the render function

2019-03-15 03:49 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +  fill: boolean = true;
That warning is legit; that means you should just write `<ControlGroup fill />` (without the assignment)

2019-03-15 03:50 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +        if (val === 1) {
No I mean, why do we need `if` there if it is always returning that value

2019-03-16 21:16 UTC, chidx commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +  fill: boolean = true;
Ok 
#TIL

2019-03-17 02:39 UTC, fushar commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +        if (val === 1) {
Ping about this?

2019-03-17 19:51 UTC, chidx commented on judgels-frontends/raphael/src/components/ProblemWorksheetCard/Bundle/ProblemStatementCard/ItemShortAnswerCard/ItemShortAnswerForm/ItemShortAnswerForm.tsx
> +        if (val === 1) {
Sorry for late response
I will remove that `if`

2019-03-17 22:33 UTC, fushar requested changes

2019-03-17 22:33 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts
> +      return 1;
Unused anymore?

2019-03-17 22:55 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts
> +      return 1;
Please just fix it in #148

2019-03-17 22:55 UTC, fushar approved these changes

2019-03-17 22:56 UTC, merged