Add regrade support for bundle item submissions
ia-toki/judgels pull request #193
Opened 2019-04-23 14:43 UTC by nathanchrs

Implements #192.

Add bundle item submissions regrade endpoints for Uriel, and regrade buttons in Raphael.

2019-04-23 16:03 UTC, fushar requested changes

2019-04-23 16:03 UTC, fushar commented on judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/submission/bundle/BaseItemSubmissionStore.java
> +    public void saveRegradeResult(String submissionJid, Grading grading) {
`updateGrading`

2019-04-23 16:44 UTC, nathanchrs commented on judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/submission/bundle/ItemSubmissionRegradeProcessor.java
> +                if (submission.getGrading().isPresent()) {
OK

2019-04-23 16:50 UTC, nathanchrs commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestItemSubmissionService.java
> +    @Consumes(APPLICATION_JSON)
Annotation removed

2019-04-23 16:50 UTC, nathanchrs commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/programming/ContestSubmissionService.java
> +    @Consumes(APPLICATION_JSON)
Annotation removed

2019-04-23 16:50 UTC, nathanchrs commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestItemSubmissionService.java
> +    @Consumes(APPLICATION_JSON)
Annotation removed

2019-04-23 16:50 UTC, nathanchrs commented on judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/programming/ContestSubmissionService.java
> +    @Consumes(APPLICATION_JSON)
Annotation removed

2019-04-23 16:54 UTC, nathanchrs commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/VerdictTag/VerdictTag.tsx
> +  if (verdict === Verdict.PENDING_REGRADE) {
OK

2019-04-23 16:57 UTC, nathanchrs commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts
> +      toastActions.showSuccessToast('Regrade in progress.');
Message changed to 'Submission regraded.'

2019-04-23 17:00 UTC, nathanchrs commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/VerdictTag/VerdictTag.tsx
> +    displayCode = <Icon icon="follower" />;
![image](https://user-images.githubusercontent.com/8141000/56600745-a8990580-6623-11e9-92fe-8e1f70afb1bd.png)
To differentiate between pending submissions (awaiting regrade) and submissions that require manual grading. The `follower` icon shows that a person needs to manually look at the submission.

2019-04-23 17:01 UTC, nathanchrs commented on judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/VerdictTag/VerdictTag.tsx
> +    displayCode = <Icon icon="follower" />;
The `refresh` icon has been changed to `time` icon

2019-04-23 17:05 UTC, nathanchrs commented on judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/submission/bundle/BaseItemSubmissionStore.java
> +    public void saveRegradeResult(String submissionJid, Grading grading) {
Renamed

2019-04-24 03:43 UTC, fushar approved these changes

2019-04-24 03:43 UTC, merged