Add Ansible playbook to download Judgels data files, DB dump and logs
ia-toki/judgels pull request #304
Opened 2020-08-16 12:23 UTC by nathanchrs

2020-08-16 14:15 UTC, fushar approved these changes

2020-08-16 14:27 UTC, fushar requested changes

2020-08-16 14:27 UTC, fushar commented on deployment/ansible/dist-example/env.yml
> +downloaded_data_dir: "{{ inventory_dir }}/contest-data"
```suggestion
dump_dir: "{{ inventory_dir }}/dump"
```

2020-08-16 14:27 UTC, fushar commented on deployment/ansible/playbooks/download-data.yml
> +- hosts: database
Filename:

`dump-data.yml`

2020-08-16 14:27 UTC, fushar commented on deployment/ansible/playbooks/download-logs.yml
> +- hosts: judgels
Filename:

`dump-logs.yml`

2020-08-16 14:46 UTC, fushar commented on deployment/ansible/playbooks/download-data.yml
> +- hosts: sandalphon
Please also dump submissions

2020-08-16 14:55 UTC, nathanchrs commented on deployment/ansible/playbooks/download-logs.yml
> +- hosts: judgels
OK

2020-08-16 14:55 UTC, nathanchrs commented on deployment/ansible/playbooks/download-data.yml
> +- hosts: sandalphon
Added

2020-08-18 14:15 UTC, fushar approved these changes

2020-08-18 14:16 UTC, merged