feat: handle upload zip with directories
ia-toki/judgels pull request #537
Opened 2023-10-19 06:56 UTC by kadeksuryam

Resolve #452

2023-10-20 11:07 UTC, kadeksuryam commented
Hello. My approach for this issue is that every file that exists in a directory will be moved to the outermost parent directory, which is the resource directory. For example, given this zip file with these files and directories:
```
dir1
  file1
  dir2
    file2
dir3
  file3
file4
```
All of the files: file1, file2, file3, and file4, will be successfully unzipped to the resource folder without the dir1, dir2, and dir3 directories. If there happens to be files with the same filename in different directories, the file from the "deepest" directory will be chosen.

What do you think? @fushar

2023-10-20 14:14 UTC, fushar commented on judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/local/LocalFileSystem.java
> +            Set<String> directories = Sets.newHashSet();
I think this whole logic can be simplified by always taking `FilenameUtils.getName(ze.getName())` as the filename for all non-directory entries. Something like (pseudocode):

```
if (ze.isDirectory()) {
  continue;
}

String filename = FilenameUtils.getName(ze.getName());
File file = new File(destDir, filename);

// etc
```

What do you think?

2023-10-21 02:14 UTC, fushar requested changes
Thanks for your contribution!

Unfortunately, this is a bit complicated. We have to ignore certain directories:

https://github.com/ia-toki/judgels/blob/314fe62f1ea69bf4bce01ec0bedb8a30b5e462b8/judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/local/LocalFileSystem.java#L33-L36

- `.gitkeep`
- `__MACOSX`: this is present when we compress the ZIP on Mac. See:

<img width="1084" alt="Screenshot 2023-10-21 at 09 07 04" src="https://github.com/ia-toki/judgels/assets/1525580/63c336e1-f198-4ffe-a8a4-5b0dd86ab38c">

So we need to ignore a file if it lives in any of the ignorable directories. Something like this:

```
String filename = FilenameUtils.getName(ze.getName());
if (IGNORABLE_FILES.stream().anyMatch(dir -> filename.contains(dir + "/"))) {
  // skip this file
}
```

---

For reference, here is the result of uploading zip files from Mac, with the current PR, which is wrong

<img width="695" alt="image" src="https://github.com/ia-toki/judgels/assets/1525580/465f8d0a-132a-4863-87cd-e5fb3cace8d4">

2023-10-21 04:40 UTC, kadeksuryam reviewed
handle file entry in ignorable dir

2023-10-21 07:06 UTC, fushar approved these changes

2023-10-21 07:07 UTC, merged