[WIP] Add regrade checkbox with dummy api
ia-toki/judgels pull request #78
Opened 2019-01-01 23:55 UTC by aguss787

2019-01-02 17:52 UTC, fushar requested changes
Please also add:

- a new button ~~"Regrade all in page"~~, instead of a confusing "select-all" checkbox. This will hit a separate endpoint, which have the same query params as the filter endpoint.

- a regrade button for each individual submission row. This will hit the regrade submissions endpoint with an array containing a single element.

2019-01-02 22:49 UTC, fushar commented
Sorry, the first item should be "Regrade all pages" (which will regrade all submissions in all pages)

2019-01-06 15:13 UTC, aguss787 commented
Admin/Supervisor display:

![image](https://user-images.githubusercontent.com/9874779/50737886-52cd5880-1200-11e9-85e3-07de8c233481.png)

2019-01-07 00:51 UTC, fushar approved these changes

2019-01-07 00:52 UTC, merged