[WIP] Add pending status to frozen icpc scoreboard
ia-toki/judgels pull request #83
Opened 2019-01-28 07:08 UTC by aguss787

2019-01-28 16:26 UTC, fushar requested changes

2019-01-28 16:26 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +        Map<String, List<Submission>> pendingSubmissionsMap = new HashMap<>();
`frozenSubmissionsMap`, to be consistent with the naming?

2019-01-28 16:26 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +                if (!submission.getLatestGrading().isPresent()) {
Put this also in filtered submissions predicate above?

2019-01-28 16:26 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +            for (Submission submission : pendingSubmissions) {
Always inline things like this in the for itself, for simple expressions

```
for (Submission submission : pendingSubmissionsMap.get(contestantJid))
```

2019-01-28 16:26 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/scoreboard/IcpcScoreboardTable/IcpcScoreboardTable.test.tsx
> +    expect(points).toEqual([['3/66', 'G 1/3', 'D 3/14', 'D 1/9'], ['1/17', 'R 1/-', 'G 1/17', 'F ?/?']]);
You're deleting a valid test case here (`X` color)

2019-01-29 02:52 UTC, fushar commented
IMPORTANT! This mark should only apply to FROZEN scoreboard. The OFFICIAL scoreboard should not be affected.

2019-01-29 08:19 UTC, aguss787 commented
> 
> 
> IMPORTANT! This mark should only apply to FROZEN scoreboard. The OFFICIAL scoreboard should not be affected.

Yup, it is

2019-01-29 15:41 UTC, fushar approved these changes
Please apply the autosuggestions and then it is good to go

2019-01-29 15:41 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +                if (isAccepted(problemStateMap.get(submission.getProblemJid()))) {
```suggestion
                if (isAccepted(problemStateMap.get(problemJid))) {
```

2019-01-29 15:41 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +                if (isAccepted(problemStateMap.get(submission.getProblemJid()))) {
```suggestion
                if (isAccepted(problemStateMap.get(problemJid))) {
```

2019-01-29 15:41 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/icpc/IcpcScoreboardProcessor.java
> +                problemStateMap.put(submission.getProblemJid(), IcpcScoreboardProblemState.FROZEN);
```suggestion
                problemStateMap.put(problemJid, IcpcScoreboardProblemState.FROZEN);
```

2019-01-30 03:54 UTC, merged