Implement GCJ style
ia-toki/judgels pull request #88
Opened 2019-02-02 14:24 UTC by aguss787

2019-02-05 11:29 UTC, fushar requested changes

2019-02-05 16:02 UTC, aguss787 commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/updater/ContestScoreboardUpdaterDispatcher.java
> +        LOGGER.info(contest.getName());
Whoops, it not supposed to be there

2019-02-07 03:47 UTC, aguss787 commented on judgels-backends/uriel/uriel-app/src/integTest/java/judgels/uriel/api/contest/problem/ContestProblemServiceIntegrationTests.java
> +                        .points(0)
No, even though it is optional, the return value will have points equals to zero. Hence, we will still need to set points to zero

2019-02-07 14:55 UTC, fushar requested changes

2019-02-07 14:55 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/problems/modules/editor/defaultContestProblemEditor.test.ts
> +describe('contestProblemValidations', () => {
```suggestion
describe('defaultContestProblemEditor', () => {
```

2019-02-07 14:55 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/problems/modules/editor/defaultContestProblemEditor.test.ts
> +  test('ValidProblemsSetData', () => {
```suggestion
  test('validator', () => {
```

2019-02-07 14:55 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/problems/ContestProblemEditDialog/ContestProblemEditDialog.tsx
> +  private updateComponents() {
```suggestion
  private updateEditor() {
```

2019-02-07 14:55 UTC, fushar commented on judgels-frontends/raphael/src/routes/uriel/contests/single/problems/ContestProblemEditDialog/ContestProblemEditDialog.tsx
> +      this.updateComponents();
```suggestion
      this.updateEditor();
```

2019-02-08 15:08 UTC, aguss787 commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/updater/ContestScoreboardUpdater.java
> +        submissions.sort(Comparator.comparingLong(Submission::getId));
Apparently it is not :/.
the list is reversed when I try it

2019-02-08 15:19 UTC, fushar approved these changes

2019-02-08 15:20 UTC, merged