scoreboard pagination
ia-toki/judgels pull request #92
Opened 2019-02-04 11:49 UTC by kevinluvian

resolve #15

2019-02-05 13:00 UTC, fushar requested changes

2019-02-05 13:00 UTC, fushar commented on judgels-frontends/raphael/.prettierrc.json
> +}
Don't remove newline

2019-02-08 15:21 UTC, fushar commented
Please rebase. There is a new contest style (GCJ), you will need to add the logic also there

2019-02-15 10:38 UTC, kevinluvian commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ScoreboardProcessor.java
> +    int getTotalEntries(Scoreboard scoreboard);
ini udah ko, totalEntriesnya gk aku ganti jadi gk ke mark outdated

2019-02-15 14:18 UTC, fushar requested changes
Almost done!

2019-02-15 14:18 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ScoreboardProcessor.java
> +        } catch (IndexOutOfBoundsException e) {
This is an antipattern (using exception for normal flow). You can always check if the index is out of bound (using `.size()`)

2019-02-15 14:18 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ScoreboardProcessor.java
> +        List partitionPage;
```suggestion
        List<?> partitionPage;
```

2019-02-15 14:18 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ContestScoreboardResource.java
> +    private static final int pageSize = 50;
```suggestion
    private static final int PAGE_SIZE = 50;
```

2019-02-15 14:18 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ScoreboardProcessor.java
> +    Scoreboard replaceEntries(Scoreboard scoreboard, List<?> entries);
```suggestion
    Scoreboard replaceEntries(Scoreboard scoreboard, List<? extends IcpcScoreboardEntry> entries);
```

2019-02-15 22:35 UTC, fushar commented on judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/scoreboard/ScoreboardProcessor.java
> +    Scoreboard replaceEntries(Scoreboard scoreboard, List<?> entries);
Sorry, cannot do this because entries do not have base interface

2019-02-15 22:35 UTC, fushar approved these changes

2019-02-15 22:36 UTC, merged